name: xeus-env
channels:
- https://repo.mamba.pm/emscripten-forge
- conda-forge
dependencies:
- python
- xeus-python
- ipython
- ipywidgets
- matplotlib
- pandas
- requests
- numpy
- pandas
- requests
- scipy
